-- MySQL Script generated by MySQL Workbench
-- Sat Feb  1 15:01:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Por Peñaranda Jonnathan & Velez Belen

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Mesa` (
  `numero` INT NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `Producto_id` INT NOT NULL,
  `Mesa_numero` INT NOT NULL,
  `orden_cobrada` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orden_Producto1_idx` (`Producto_id` ASC),
  INDEX `fk_Orden_Mesa1_idx` (`Mesa_numero` ASC),
  CONSTRAINT `fk_Orden_Producto1`
    FOREIGN KEY (`Producto_id`)
    REFERENCES `restaurante`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orden_Mesa1`
    FOREIGN KEY (`Mesa_numero`)
    REFERENCES `restaurante`.`Mesa` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Mesa` (
  `numero` INT NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NULL,
  `Cliente_id` INT NOT NULL,
  `total` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_id` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `restaurante`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Factura_has_Orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Factura_has_Orden` (
  `id` INT NOT NULL,
  `Factura_id` INT NOT NULL,
  `Orden_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Factura_has_Orden_Orden1_idx` (`Orden_id` ASC),
  INDEX `fk_Factura_has_Orden_Factura1_idx` (`Factura_id` ASC),
  CONSTRAINT `fk_Factura_has_Orden_Factura1`
    FOREIGN KEY (`Factura_id`)
    REFERENCES `restaurante`.`Factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Orden_Orden1`
    FOREIGN KEY (`Orden_id`)
    REFERENCES `restaurante`.`Orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
